INSERT INTO PRODUTOS
SELECT CODIGO_DO_PRODUTO AS CODIGO, NOME_DO_PRODUTO AS DESCRITOR 
, SABOR, TAMANHO, EMBALAGEM, PRECO_DE_LISTA AS PRECO_LISTA
FROM TABELA_DE_PRODUTOS;

ALTER TABLE PRODUTOS MODIFY (EMBALAGEM VARCHAR(50));

SELECT * FROM TABELA_DE_PRODUTOS;

INSERT INTO PRODUTOS
SELECT CODIGO_DO_PRODUTO AS CODIGO, NOME_DO_PRODUTO AS DESCRITOR 
, SABOR, TAMANHO, EMBALAGEM, PRECO_DE_LISTA AS PRECO_LISTA
FROM TABELA_DE_PRODUTOS WHERE CODIGO_DO_PRODUTO <> 1040107;

SELECT * FROM PRODUTOS;


SELECT * FROM CLIENTES;

INSERT INTO CLIENTES
VALUES('1471156710', 'Erica Carvalho', 'Rua Iriqutia', 'Jardins', 'Sao Paulo',
'SP', '80012212',TO_DATE('1990-09-01', 'YYYY-MM-DD'), 27, 'F',
170000, 24500, 0);

SELECT * FROM TABELA_DE_CLIENTES;

SELECT CPF, NOME, ENDERECO_1 AS ENDERECO, BAIRRO, CIDADE, ESTADO , CEP
, DATA_DE_NASCIMENTO AS DATA_NASCIMENTO, IDADE, SEXO, LIMITE_DE_CREDITO AS LIMITE_CREDITO
, VOLUME_DE_COMPRA AS VOLUME_COMPRA , PRIMEIRA_COMPRA
FROM TABELA_DE_CLIENTES;

INSERT INTO CLIENTES
SELECT CPF, NOME, ENDERECO_1 AS ENDERECO, BAIRRO, CIDADE, ESTADO , CEP
, DATA_DE_NASCIMENTO AS DATA_NASCIMENTO, IDADE, SEXO, LIMITE_DE_CREDITO AS LIMITE_CREDITO
, VOLUME_DE_COMPRA AS VOLUME_COMPRA , PRIMEIRA_COMPRA
FROM TABELA_DE_CLIENTES where cpf <> '1471156710';


