

CREATE OR REPLACE FUNCTION categoria_cliente
(p_FATURAMENTO_PREVISTO in CLIENTE.FATURAMENTO_PREVISTO%TYPE)
RETURN CLIENTE.CATEGORIA%TYPE
IS
    v_CATEGORIA CLIENTE.CATEGORIA%TYPE;
BEGIN
 IF p_FATURAMENTO_PREVISTO < 10000 THEN
        v_CATEGORIA := 'PEQUENO';
    ELSIF p_FATURAMENTO_PREVISTO < 50000 THEN
        v_CATEGORIA := 'MÉDIO';
    ELSIF p_FATURAMENTO_PREVISTO < 100000 THEN
        v_CATEGORIA := 'MÉDIO GRANDE';
    ELSE 
        v_CATEGORIA := 'GRANDE';
    END IF;
    RETURN v_CATEGORIA;
END;

    -- EXECUTANDO FUNCAO
    VARIABLE g_CATEGORIA VARCHAR2(100);
    
    EXECUTE : g_CATEGORIA := categoria_cliente(110000);
    
    PRINT G_CATEGORIA;