

SELECT * FROM CLIENTE;

SELECT SUBSTR(CNPJ, 1,3) || '/' || SUBSTR(CNPJ,4,2) FROM CLIENTE;

CREATE OR REPLACE PROCEDURE FORMATA_CNPJ
(p_CNPJ IN OUT CLIENTE.CNPJ%TYPE)
IS
BEGIN
    p_CNPJ := SUBSTR(p_CNPJ, 1,3) || '/' || SUBSTR(p_CNPJ,4,2);
END;

VARIABLE g_CNPJ VARCHAR2(10)


EXECUTE :g_CNPJ := '12345'

PRINT :g_CNPJ

EXECUTE FORMATA_CNPJ(:g_CNPJ);

PRINT :g_CNPJ