DECLARE
    v_ID SEGMERCADO.ID%type := 3;
    v_DESCRICAO SEGMERCADO.DESCRICAO%type := UPPER('ESPORTISTAS');
BEGIN
    DELETE FROM SEGMERCADO
    WHERE ID = v_ID;
    COMMIT;
END;


SELECT * FROM SEGMERCADO;