SET SERVEROUTPUT ON;

DECLARE 
    CURSOR cur_CLIENTE IS SELECT ID, RAZAO_SOCIAL FROM CLIENTE;
    v_ID CLIENTE.ID %TYPE;
    v_RAZAO_SOCIAL CLIENTE.RAZAO_SOCIAL%TYPE;
BEGIN
    OPEN cur_CLIENTE;
    LOOP
        FETCH cur_CLIENTE INTO v_ID, v_RAZAO_SOCIAL;
    EXIT WHEN   cur_CLIENTE%NOTFOUND;
        dbms_output.put_line ('ID = ' || v_ID);
        DBMS_OUTPUT.PUT_LINE('Razão Social = ' || v_RAZAO_SOCIAL);
    END LOOP;
    CLOSE cur_CLIENTE;
END;