SELECT CPF, COUNT(*) FROM NOTAS_FISCAIS
WHERE TO_CHAR(DATA_VENDA, 'YYYY') = '2016'
GROUP BY CPF
HAVING COUNT(*) > 2000;

SELECT X.CPF, X.CONTADOR FROM 
(SELECT CPF, COUNT(*) AS CONTADOR FROM NOTAS_FISCAIS
WHERE TO_CHAR(DATA_VENDA, 'YYYY') = 2016
GROUP BY CPF) X WHERE X.CONTADOR > 2000;

SELECT X.CPF, X.CONTADOR FROM
(SELECT CPF, COUNT(*) AS CONTADOR FROM NOTAS_FISCAIS
WHERE TO_CHAR(DATA_VENDA, 'YYYY') = 2016
GROUP BY CPF) X WHERE X.CONTADOR > 2000;

SELECT CPF FROM notas_fiscais;

SELECT EMBALAGEM, SUM(PRECO_DE_LISTA) AS SOMA_PRECO
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM;

SELECT Z.EMBALAGEM, Z.SOMA_PRECO FROM (SELECT EMBALAGEM, SUM(PRECO_DE_LISTA) AS SOMA_PRECO
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM) Z
WHERE Z.SOMA_PRECO <= 80;

SELECT EMBALAGEM, SUM(PRECO_DE_LISTA) AS SOMA_PRECO
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM;

SELECT * FROM  VW_EMBALAGENS
WHERE SOMA_PRECO <= 80;

SELECT * FROM TABELA_DE_PRODUTOS A
INNER JOIN VW_EMBALAGENS B ON
A.EMBALAGEM = B.EMBALAGEM;

SELECT A.MATRICULA, B.NOME, COUNT(*) FROM NOTAS_FISCAIS A
INNER JOIN TABELA_DE_VENDEDORES B
ON A.MATRICULA = B.MATRICULA
GROUP BY A.MATRICULA, B.NOME;