SELECT NOME FROM TABELA_DE_CLIENTES;

SELECT NOME, UPPER(NOME) FROM TABELA_DE_CLIENTES;

SELECT NOME, LOWER(NOME) FROM TABELA_DE_CLIENTES;

SELECT NOME_DO_PRODUTO, INITCAP(NOME_DO_PRODUTO) FROM TABELA_DE_PRODUTOS;

SELECT CONCAT(ENDERECO_1, BAIRRO) FROM TABELA_DE_CLIENTES;

SELECT NOME, 'Endere?o: ' || ENDERECO_1 || ' ' || BAIRRO || ' ' || CIDADE || ' ' || ESTADO || ', CEP: ' || CEP
FROM TABELA_DE_CLIENTES;

SELECT NOME_DO_PRODUTO, LPAD(NOME_DO_PRODUTO, 60, '*') FROM TABELA_DE_PRODUTOS;

SELECT NOME_DO_PRODUTO, RPAD(NOME_DO_PRODUTO, 60, '*') FROM TABELA_DE_PRODUTOS;

SELECT NOME_DO_PRODUTO, SUBSTR(NOME_DO_PRODUTO,3,5) FROM TABELA_DE_PRODUTOS;

SELECT NOME_DO_PRODUTO, INSTR(NOME_DO_PRODUTO, '-') FROM TABELA_DE_PRODUTOS;

SELECT LTRIM('           AAAAAAA') FROM DUAL;

SELECT RTRIM('AAAAAAA         ') FROM DUAL;

SELECT NOME_DO_PRODUTO, REPLACE(REPLACE(NOME_DO_PRODUTO, 'Litro', 'L'),'Ls','L') FROM TABELA_DE_PRODUTOS;

-- Endereço Completo
SELECT NOME, 'ENDEREÇO:' || ENDERECO_1 || ' ' || ENDERECO_2 || ' ' || BAIRRO || ' ' || CIDADE || ' ' || ESTADO || ' ' || 'CEP:' || CEP AS ENDERECO_COMPLETO
FROM TABELA_DE_CLIENTES;
--Mostra Idade Atual--
SELECT NOME, TRUNC( MONTHS_BETWEEN (SYSDATE, DATA_DE_NASCIMENTO)/12) AS IDADE
FROM TABELA_DE_CLIENTES;

SELECT ROUND(3.4) FROM DUAL;
SELECT TRUNC(3.6) FROM DUAL;

-- CALCULA O VALOR DO IMPOSTO EM 2016
SELECT TO_CHAR(DATA_VENDA, 'YYYY') AS ANO,
FLOOR(SUM(IMPOSTO * (QUANTIDADE * PRECO))) AS IMPOSTO
FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
WHERE TO_CHAR(DATA_VENDA, 'YYYY') = 2016
GROUP BY TO_CHAR(DATA_VENDA, 'YYYY');

SELECT TO_DATE('12/11/2019', 'DD/MM/YYYY') FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MM:SS AM') FROM DUAL;

SELECT EXTRACT(MONTH FROM TO_DATE('12/11/2019', 'DD/MM/YYYY')) FROM DUAL;