GRANT EXECUTE ON ATUALIZAR_CLI_SEG_MERCADO TO USER_APP;
GRANT EXECUTE ON ATUALIZAR_FATURAMENTO_PREVISTO TO USER_APP;
GRANT EXECUTE ON EXCLUIR_CLIENTE TO USER_APP;
GRANT EXECUTE ON INCLUIR_CLIENTE TO USER_APP;

GRANT SELECT ON CLIENTE TO USER_APP;